name: pylint-update-readme
author: 'Tadgh Henry'
description: "Updates a repository's readme with the output from pylint"
branding:
  icon: 'type'
  color: 'blue'

#Provide the folder that contains your python files, or /** if they are in the root
on:
  push:
    paths:
      - "snake_says_hello/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    env:
      # The folder containing your python files, normally the same path where push events are monitored
      PYTHON_FOLDER: "snake_says_hello"
      # Path to the folder containing your pip requirments file
      REQUIREMENTS_FOLDER: "snake_says_hello"
      # This will be a string in your readme, your recommendations will be appended below it and EXISTING content BELOW is OVERWRITTEN
      STRING_TO_ADD: "The following changes should be made."
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "${{ env.REQUIREMENTS_FOLDER}}/requirements.txt"
      - name: Run pylint.
        run: |
          pylint -j 0 --fail-under=8.0 "${{ env.PYTHON_FOLDER }}/*.py" > pylint_recommendations.txt
        working-directory: ${{ github.workspace }}
        continue-on-error: true

      - name: Overwrite linting recommendations in README.
        run: |
          awk '/${{ env.STRING_TO_ADD}}/{print; print "```python"; system("cat pylint_recommendations.txt"); print "```"; exit} 1' README.md > README.md.tmp
          mv README.md.tmp README.md
        working-directory: ${{ github.workspace }}
        continue-on-error: true

      - name: Commit and push pylint recommendations.
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add README.md
          git diff-index --quiet HEAD || git commit -m "Update README with latest linting recommendations"
          git push
        working-directory: ${{ github.workspace }}
